# 项目配置: 名称、日志目录
project:
  name: air-admin
  log-directory: ${localPath:/home}/logs/smart_admin_v3/${project.name}/${spring.profiles.active}

# 项目端口和url根路径
server:
  port: 8080
  servlet:
    context-path: /

# 环境
spring:
  profiles:
    active: '@profiles.active@'