server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://192.168.2.175/oims?currentSchema=public
    username: postgres
    password: z@king.com@123
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: 192.168.2.175
      port: 6379
      database: 0
  web:
    resources:
      static-locations: classpath:/templates
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

