server:
  port: 8081
  address: 0.0.0.0 # 允许局域网访问
spring:
  datasource:
    url: jdbc:postgresql://192.168.2.175/mzgl?currentSchema=public
    username: postgres
    password: z@king.com@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: 192.168.2.175
      port: 6379
      database: 0
      timeout: 1800000
      password:
      jedis:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: iking@.com


minio:
  endpoint: http://192.168.2.175:9001
  accessKey: admin
  secretKey: admin123
  bucketName: mzgl