spring:
  datasource:
    url: jdbc:postgresql://192.168.2.175/oims?public=public
    username: postgres
    password: z@king.com@123
    driver-class-name: org.postgresql.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
